### ISSUE TITLE
TestNearest failed with annotated PHP test

### ISSUE THREAD

**Issue by jesseleite** [janko/vim-test#361]
I can still test nearest on this...
```php
public function test_it_still_does_a_thing()
{
    // this still works
}
```

But can no longer test nearest on this...
```php
/** @test */
public function it_does_a_thing()
{
    // no longer works
}
```

The latter is a valid PHPUnit convention, and worked until I recently updated vim-test 🤔 

Thoughts on this?

**Comment by janko** [comment]
That could be related to https://github.com/janko/vim-test/pull/349. @elythyr any ideas?

**Comment by elythyr** [comment]
Hi there,

It seems this way, after removing the merge from #349 there is no error anymore.

This seems to be because your phpdoc is on only one line.
If you pass it on multple lines:
```php
/**
 * @test
*/
```
It will work fine.
Just the time to fix it, will add a new test for it.

Will try to propose you a fix in the afternoon.

**Comment by jesseleite** [comment]
Ah cool, thanks for looking into!

**Comment by janko** [comment]
This should be fixed by https://github.com/janko/vim-test/pull/362
