### ISSUE TITLE
All tests always run for cargo

### ISSUE THREAD

**Issue by sivakov512** [janko/vim-test#389]
Hi!
Thank you for awesome plugin, it realy helpful!

All project tests always run regardless of the command I run.

**Comment by janko** [comment]
Yes, the cargo vim-test runner currently doesn't handle test files or nearest tests. I assume that's because `cargo test` didn't support this functionality at the time of writing. Has this changed?

**Comment by sivakov512** [comment]
Yes. You can pass any part of full test name (module::[all modules inside]::test_name) as argument to `cargo test` and it will run all matched tested

**Comment by janko** [comment]
Ok, I don’t have time to work on vim-test anymore, but I’ll gladly merge pull requests.

**Comment by sivakov512** [comment]
I'm not experienced with VimL, myabe you can show some example in existing code that can help me?

**Comment by janko** [comment]
I believe the [mocha runner](https://github.com/janko/vim-test/blob/master/autoload/test/javascript/mocha.vim) might provide a good template.

The `build_position` function is the one that builds command-line arguments based on whether the user executed `:TestSuite`, `:TestFile`, or `:TestNearest` command. https://github.com/janko/vim-test/blob/fc4f15e99e45fcb24ef9069a0726ceca5bd601ee/autoload/test/javascript/mocha.vim#L10-L23

Since Mocha doesn't support line numbers but supports regexes, the nearest test is determined by parsing the current buffer using regexes: https://github.com/janko/vim-test/blob/fc4f15e99e45fcb24ef9069a0726ceca5bd601ee/autoload/test/javascript.vim#L1-L4

The `test#base#nearest_test` function already exists for searching files, you just need to supply the regexes. Hopefully the documentation of that method will shed some more light on how it works: https://github.com/janko/vim-test/blob/fc4f15e99e45fcb24ef9069a0726ceca5bd601ee/autoload/test/base.vim#L50-L79

**Comment by codeinabox** [comment]
@sivakov512 let me know if you'd like a hand with this, I am happy to help
